-- CREATE DATABASE --
CREATE DATABASE IF NOT EXISTS ${hiveconf:DATABASE};
USE ${hiveconf:DATABASE};


-- DROP TABLES --
DROP TABLE IF EXISTS LND_INV_ONHAND_DLY;
DROP TABLE IF EXISTS LND_INV_ONHAND_MTHLY;
DROP TABLE IF EXISTS LND_INV_INTRANSIT_DLY;
DROP TABLE IF EXISTS LND_SAP_PLANT_COMPANY_MASTER;
DROP TABLE IF EXISTS LND_SAP_MATERIAL_MASTER;
DROP TABLE IF EXISTS LND_PRIMARY_PLANT_LOOKUP;
DROP TABLE IF EXISTS STG_INV_ONHAND_DLY;
DROP TABLE IF EXISTS STG_INV_ONHAND_MTHLY;
DROP TABLE IF EXISTS STG_INV_INTRANSIT_DLY;
DROP TABLE IF EXISTS STG_SAP_PLANT_COMPANY_MASTER;
DROP TABLE IF EXISTS STG_SAP_MATERIAL_MASTER_HISTORY;
DROP TABLE IF EXISTS STG_SAP_MATERIAL_MASTER;
DROP TABLE IF EXISTS STG_INV_ONHAND_INTRA;
DROP TABLE IF EXISTS STG_INV_INTER_INTRANSIT;
DROP TABLE IF EXISTS STG_SAP_MATERIAL_DETAIL;
DROP TABLE IF EXISTS STG_PRIMARY_PLANT_LOOKUP;
DROP TABLE IF EXISTS STG_INV_VISIBILITY;
DROP TABLE IF EXISTS ERR_INV_VISIBILITY;
DROP TABLE IF EXISTS TMP_MATERIAL_COST;
DROP TABLE IF EXISTS TMP_MAT_PRIM_PLANT_COST;
DROP TABLE IF EXISTS STG_FIN_MANUAL_ADJUSTMENTS;
DROP TABLE IF EXISTS STG_PLAN_UPD_GAP;
DROP TABLE IF EXISTS INV_VISIBILITY_COMMENTARY_F;
DROP TABLE IF EXISTS ACTUAL_INV_VISIBILITY_F;
DROP TABLE IF EXISTS PLN_UPD_GAP_INV_VISIBILITY_F;
DROP TABLE IF EXISTS FIN_ADJUST_INV_VISIBILITY_F;
DROP TABLE IF EXISTS TMP_INV_VISIBILITY;
DROP TABLE IF EXISTS STG_AUDIT_DM_LOAD_TIME;
DROP TABLE IF EXISTS INV_VISIBILITY_VARNC_F;
DROP TABLE IF EXISTS IVIS_AFF_EMAIL_GRP;
DROP TABLE IF EXISTS REPORT_USER_SECURITY;
DROP TABLE IF EXISTS COST_OVERRIDE_HISTORY;
DROP TABLE IF EXISTS COST_OVERRIDE;


-- CREATE TABLES --
CREATE EXTERNAL TABLE LND_INV_ONHAND_DLY 
(
USER STRING,
DATE INT,
TIME INT,
REC_NUM INT,
TABLE STRING,
MATERIAL STRING,
PLANT STRING,
SLOC STRING,
BATCH STRING,
SPEC_STOCK STRING,
VENDOR STRING,
CUSTOMER STRING,
NONBATCH_UNRESTR_QTY DOUBLE,
NONBATCH_QI_QTY DOUBLE,
NONBATCH_RESTR_QTY DOUBLE,
NONBATCH_BLOCKED_QTY DOUBLE,
NONBATCH_RETURN_QTY DOUBLE,
NONBATCH_INTRANS_QTY DOUBLE,
UNRESTR_QTY DOUBLE,
QI_QTY DOUBLE,
RESTR_QTY DOUBLE,
BLOCKED_QTY DOUBLE,
RETURN_QTY DOUBLE,
INTRANS_QTY DOUBLE,
CUSTOMER_UNRESTR_QTY DOUBLE,
CUSTOMER_QI_QTY DOUBLE,
CUSTOMER_RESTR_QTY DOUBLE,
CUSTOMER_BLOCKED_QTY DOUBLE,
VENDOR_UNRESTR_QTY DOUBLE,
VENDOR_QI_QTY DOUBLE,
VENDOR_RESTR_QTY DOUBLE,
TOTAL_QTY DOUBLE,
BASE_UOM STRING,
STD_COST DOUBLE,
TOTAL_VALUE DOUBLE
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/landing/sap/lnd_inv_onhand_dly/'
tblproperties ("skip.header.line.count"="1");

CREATE EXTERNAL TABLE LND_INV_ONHAND_MTHLY 
(
USER STRING,
DATE INT,
TIME INT,
REC_NUM INT,
TABLE STRING,
MATERIAL STRING,
PLANT STRING,
SLOC STRING,
BATCH STRING,
SPEC_STOCK STRING,
VENDOR STRING,
CUSTOMER STRING,
YEAR INT,
PERIOD INT,
UNRESTR_QTY DOUBLE,
QI_QTY DOUBLE,
RESTR_QTY DOUBLE,
BLOCKED_QTY DOUBLE,
RETURN_QTY DOUBLE,
INTRANS_QTY DOUBLE,
TOTAL_QTY DOUBLE,
BASE_UOM STRING,
STD_COST DOUBLE,
TOTAL_VALUE DOUBLE
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/landing/sap/lnd_inv_onhand_mthly/'
tblproperties ("skip.header.line.count"="1");

CREATE EXTERNAL TABLE LND_INV_INTRANSIT_DLY
(
USER STRING,
DATE INT,
TIME INT,
REC_NUM INT,
MATERIAL STRING,
PLANT INT,
PO_DOC STRING,
PO_ITEM STRING,
SUPPL_PLANT INT,
SPECIAL_STOCK STRING,
QTY DOUBLE,
BASE_UOM STRING,
INTRANS_TYP INT
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/landing/sap/lnd_inv_intransit_dly/'
tblproperties ("skip.header.line.count"="1");

CREATE EXTERNAL TABLE LND_SAP_PLANT_COMPANY_MASTER
(
USER STRING,
DATE INT,
TIME INT,
REC_NUM INT,
PLANT INT,
NAME STRING,
VALUATION_AREA STRING,
COMPANY_CODE INT,
PLANT_CUST STRING,
PLANT_VENDOR STRING,
AFF_CODE STRING,
WAREHOUSE STRING,
CURRENCY STRING
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/landing/sap/lnd_sap_plant_company_master/'
tblproperties ("skip.header.line.count"="1");

CREATE EXTERNAL TABLE LND_SAP_MATERIAL_MASTER
(
MATNR STRING,
WERKS INT,
LVORM STRING,
MTART STRING,
MEINS STRING,
XCHPF STRING,
MAKTX STRING,
D56 STRING
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/landing/sap/lnd_sap_material_master/'
tblproperties ("skip.header.line.count"="1");

CREATE EXTERNAL TABLE LND_PRIMARY_PLANT_LOOKUP
(
PLANT INT,
NAME STRING,
AFFILIATE_CODE STRING,
VALUATION_AREA INT,
SALES_ORG INT,
COMPANY_CODE INT,
DISPLAY_NAME STRING,
PRIMARY_IND STRING,
GROUP_NUM INT
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/landing/sap/lnd_primary_plant_lookup/'
tblproperties ("skip.header.line.count"="1");

CREATE EXTERNAL TABLE STG_INV_ONHAND_DLY 
(
SAP_TABLE STRING,
MATERIAL_ID STRING,
PLANT_ID STRING,
STORAGE_LOC STRING,
BATCH STRING,
SPEC_STOCK STRING,
VENDOR STRING,
CUSTOMER STRING,
UNRESTR_QTY DOUBLE,
QI_QTY DOUBLE,
RESTR_QTY DOUBLE,
BLOCKED_QTY DOUBLE,
RETURN_QTY DOUBLE,
INTRANS_QTY DOUBLE,
TOTAL_STOCK_QTY DOUBLE,
BASE_UOM STRING,
STD_COST DOUBLE,
TOTAL_VALUE DOUBLE,
INSERT_DT DATE,
CREATED_BY STRING
)
STORED AS AVRO
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/ivis/staging/hive/selfservice/stg_inv_onhand_dly/';

CREATE EXTERNAL TABLE STG_INV_ONHAND_MTHLY 
(
SAP_TABLE STRING,
MATERIAL_ID STRING,
PLANT_ID STRING,
STORAGE_LOC STRING,
BATCH STRING,
SPEC_STOCK STRING,
VENDOR STRING,
CUSTOMER STRING,
YEAR INT,
PERIOD INT,
UNRESTR_QTY DOUBLE,
QI_QTY DOUBLE,
RESTR_QTY DOUBLE,
BLOCKED_QTY DOUBLE,
RETURN_QTY DOUBLE,
INTRANS_QTY DOUBLE,
TOTAL_STOCK_QTY DOUBLE,
BASE_UOM STRING,
STD_COST DOUBLE,
TOTAL_VALUE DOUBLE,
INSERT_DT DATE,
CREATED_BY STRING
)
STORED AS AVRO
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/ivis/staging/hive/selfservice/stg_inv_onhand_mthly/';

CREATE EXTERNAL TABLE STG_INV_INTRANSIT_DLY
(
MATERIAL_ID STRING,
PLANT_ID INT,
PO_DOC STRING,
PO_ITEM STRING,
SUPPL_PLANT INT,
SPECIAL_STOCK STRING,
QTY DOUBLE,
BASE_UOM STRING,
STD_COST DOUBLE,
INTRANS_TYP INT,
INSERT_DT DATE,
CREATED_BY STRING
)
PARTITIONED BY (YEAR INT, PERIOD INT)
STORED AS AVRO
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/ivis/staging/hive/selfservice/stg_inv_intransit_dly/';

CREATE EXTERNAL TABLE STG_SAP_PLANT_COMPANY_MASTER
(
PLANT_ID INT,
NAME STRING,
VALUATION_AREA STRING,
COMPANY_CODE INT,
PLANT_CUST STRING,
PLANT_VENDOR STRING,
AFF_CODE STRING,
WAREHOUSE STRING,                                                   
CURRENCY STRING,
INSERT_DT DATE,
CREATED_BY STRING
)
STORED AS AVRO
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/ivis/staging/hive/selfservice/stg_sap_plant_company_master/';

CREATE EXTERNAL TABLE STG_SAP_MATERIAL_MASTER_HISTORY
(
MATERIAL_ID STRING,
PLANT_ID INT,
MAT_DEL_FLG STRING,
MATERIAL_TYP STRING,
BASE_UOM STRING,
BATCH_MGN_IND STRING,
MATERIAL_DESC STRING,
SAP_D56_ITEM_NO STRING,
WEB_SAP_D56_ITEM_NO STRING,
INSERT_DT STRING,
CREATED_BY STRING
)
STORED AS PARQUET
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/ivis/staging/hive/selfservice/stg_sap_material_master_history/';

CREATE EXTERNAL TABLE STG_SAP_MATERIAL_MASTER
(
MATERIAL_ID STRING,
PLANT_ID INT,
MAT_DEL_FLG STRING,
MATERIAL_TYP STRING,
BASE_UOM STRING,
BATCH_MGN_IND STRING,
MATERIAL_DESC STRING,
SAP_D56_ITEM_NO STRING,
WEB_SAP_D56_ITEM_NO STRING,
INSERT_DT DATE,
CREATED_BY STRING
)
STORED AS AVRO
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/ivis/staging/hive/selfservice/stg_sap_material_master/';

CREATE EXTERNAL TABLE STG_INV_ONHAND_INTRA
(
MATERIAL_ID STRING,
MATERIAL_DESC STRING,
MATERIAL_TYP STRING,
PLANT_ID STRING,
COMPANY_CDE STRING,
WAREHOUSE_CDE STRING,
SAP_D56_ITEM_NO STRING,
JDA_AFF_CDE STRING,
STD_COST DOUBLE,
BASE_UOM STRING,
CURRENCY STRING,
TOTAL_STOCK_QTY	DOUBLE,
AMT_LOCAL_CURR DOUBLE,
INVENTORY_TYP STRING,
ACTUAL_YEAR_PERIOD STRING,
INSERT_DT DATE,
CREATED_BY STRING
)
PARTITIONED BY (YEAR INT, PERIOD INT)
STORED AS AVRO
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/ivis/staging/hive/rollup/stg_inv_onhand_intra/';

CREATE EXTERNAL TABLE STG_INV_INTER_INTRANSIT
(
MATERIAL_ID	STRING,
MATERIAL_DESC STRING,
MATERIAL_TYP STRING,
PLANT_ID STRING,
SUPPLY_PLANT_ID	STRING,
SUPPLY_COMPANY_CDE STRING,
COMPANY_CDE	STRING,
WAREHOUSE_CDE STRING,
SAP_D56_ITEM_NO	STRING,
JDA_AFF_CDE	STRING,
STD_COST DOUBLE,
BASE_UOM STRING,
CURRENCY STRING,
TOTAL_STOCK_QTY	DOUBLE,
AMT_LOCAL_CURR DOUBLE,
INVENTORY_TYP STRING,
INSERT_DT DATE,
CREATED_BY STRING
)
PARTITIONED BY (YEAR INT, PERIOD INT)
STORED AS AVRO
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/ivis/staging/hive/rollup/stg_inv_inter_intransit/';

CREATE EXTERNAL TABLE STG_SAP_MATERIAL_DETAIL
(
MATERIAL_NO	STRING,
D56_ITEM_NO	STRING,
SAP_D56_ITEM_NO	STRING,
COMPANY_CODE STRING,
PLANT_ID INT,
SUPPLY_PLANT_ID	INT,
SUPPLY_PLANT_COMPANY_CODE STRING,
JDA_AFFILIATE_CODE STRING,
MATERIAL_DESCRIPTION STRING,
MATERIAL_TYPE STRING,
STANDARD_COST DOUBLE,
CURRENCY STRING,
BASE_UOM STRING,
INSERT_DT DATE,
CREATED_BY STRING
)
STORED AS AVRO
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/ivis/staging/hive/rollup/stg_sap_material_detail/';

CREATE EXTERNAL TABLE STG_PRIMARY_PLANT_LOOKUP
(
PLANT INT,
NAME STRING,
AFFILIATE_CODE STRING,
VALUATION_AREA INT,
SALES_ORG INT,
COMPANY_CODE INT,
DISPLAY_NAME STRING,
PRIMARY_IND STRING,
GROUP_NUM INT,
INSERT_DT DATE,
CREATED_BY STRING
)
STORED AS AVRO
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/ivis/staging/hive/rollup/stg_primary_plant_lookup/';

CREATE EXTERNAL TABLE STG_INV_VISIBILITY
(
MATERIAL_ID	STRING,
MATERIAL_DESC STRING,
MATERIAL_TYP STRING,
PLANT_ID STRING,
COMPANY_CDE	STRING,
SUPPLY_PLANT_ID	STRING,
SUPPLY_COMPANY_CDE STRING,
WAREHOUSE_CDE STRING,
JDA_D56_ITEM_NO STRING,
SAP_D56_ITEM_NO	STRING,
JDA_AFF_CDE	STRING,
STD_COST DOUBLE,
BASE_UOM STRING,
AMT_LOCAL_CURR DOUBLE,
CURRENCY STRING,
TOTAL_STOCK_QTY	DOUBLE,
COST_OVERRIDE_FLG STRING,
INSERT_DT DATE,
CREATED_BY STRING
)
PARTITIONED BY (INVENTORY_TYP STRING, YEAR INT, PERIOD INT)
STORED AS AVRO
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/ivis/staging/hive/rollup/stg_inv_visibility/';

CREATE EXTERNAL TABLE ERR_INV_VISIBILITY
(
MATERIAL_ID	STRING,
MATERIAL_DESC STRING,
MATERIAL_TYP STRING,
PLANT_ID STRING,
COMPANY_CDE	STRING,
SUPPLY_PLANT_ID	STRING,
SUPPLY_COMPANY_CDE STRING,
WAREHOUSE_CDE STRING,
JDA_D56_ITEM_NO STRING,
SAP_D56_ITEM_NO	STRING,
JDA_AFF_CDE	STRING,
STD_COST DOUBLE,
BASE_UOM STRING,
AMT_LOCAL_CURR DOUBLE,
CURRENCY STRING,
TOTAL_STOCK_QTY	DOUBLE,
COST_OVERRIDE_FLG STRING,
INSERT_DT DATE,
CREATED_BY STRING
)
PARTITIONED BY (INVENTORY_TYP STRING, YEAR INT, PERIOD INT)
STORED AS AVRO
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/ivis/staging/hive/rollup/err_inv_visibility/';

CREATE EXTERNAL TABLE TMP_MATERIAL_COST
(
MATERIAL STRING,
PLANT STRING,
PRIMARY_PLANT STRING,
STD_COST DOUBLE,
BASE_UOM STRING,
YEAR int,
PERIOD int
)
STORED AS AVRO
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/ivis/temp/tmp_material_cost';

CREATE EXTERNAL TABLE TMP_MAT_PRIM_PLANT_COST
(
MATERIAL STRING,
PRIMARY_PLANT STRING,
STD_COST DOUBLE,
BASE_UOM STRING,
YEAR int,
PERIOD int
)
STORED AS AVRO
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/ivis/temp/tmp_mat_prim_plant_cost';

CREATE EXTERNAL TABLE STG_FIN_MANUAL_ADJUSTMENTS
( 
AFFILIATE_CODE STRING,
TYPE STRING,
MONTH STRING,
YEAR STRING,
MATERIAL_NO STRING,
D56_ITEM_NO STRING,
AFFILIATE_DESC STRING,
COMPANY_CODE STRING,
PLANT_ID STRING,
GROUP_DESC STRING,
ADJUSTED_VALUE_USD STRING,
COMMENT STRING,
CREATED_BY STRING,
CREATED_DATE STRING
)
STORED AS AVRO
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/ivis/staging/hive/selfservice/stg_fin_manual_adjustments/';

CREATE EXTERNAL TABLE STG_PLAN_UPD_GAP
(
AFFILIATE_CODE STRING,
TYPE STRING,
YEAR STRING,
SAP_MATERIAL_NO STRING,
D56_ITEM_NO STRING,
AFFILIATE_DESC STRING,
COMPANY_CODE STRING,
PLANT_ID STRING,
GROUP_DESC STRING,
STANDARD_COST_USD STRING,
STANDARD_COST_LC STRING,
LOCAL_CURRENCY STRING,
UNITS_JAN STRING,
UNITS_FEB STRING,
UNITS_MAR STRING,
UNITS_APR STRING,
UNITS_MAY STRING,
UNITS_JUN STRING,
UNITS_JUL STRING,
UNITS_AUG STRING,
UNITS_SEP STRING,
UNITS_OCT STRING,
UNITS_NOV STRING,
UNITS_DEC STRING,
LOCAL_VAL_JAN STRING,
LOCAL_VAL_FEB STRING,
LOCAL_VAL_MAR STRING,
LOCAL_VAL_APR STRING,
LOCAL_VAL_MAY STRING,
LOCAL_VAL_JUN STRING,
LOCAL_VAL_JUL STRING,
LOCAL_VAL_AUG STRING,
LOCAL_VAL_SEP STRING,
LOCAL_VAL_OCT STRING,
LOCAL_VAL_NOV STRING,
LOCAL_VAL_DEC STRING,
USD_VAL_JAN STRING,
USD_VAL_FEB STRING,
USD_VAL_MAR STRING,
USD_VAL_APR STRING,
USD_VAL_MAY STRING,
USD_VAL_JUN STRING,
USD_VAL_JUL STRING,
USD_VAL_AUG STRING,
USD_VAL_SEP STRING,
USD_VAL_OCT STRING,
USD_VAL_NOV STRING,
USD_VAL_DEC STRING,
COMMENT STRING,
CREATED_BY STRING,
CREATED_DATE STRING
)
STORED AS AVRO
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/ivis/staging/hive/selfservice/stg_plan_upd_gap/';

CREATE EXTERNAL TABLE INV_VISIBILITY_COMMENTARY_F
(
AFFILIATE_CODE STRING,
GROUP_DESC STRING,
AFFILIATE_DESC STRING,
PLANT_ID STRING,
COMPANY_CODE STRING,
ACTUAL_BOH_ACT_BK_USD DOUBLE,
ACTUAL_BOH_PLN_BK_USD DOUBLE,
ACTUAL_BOH_UPD_BK_USD DOUBLE,
NET_BOH_PLN_USD DOUBLE,
NET_BOH_ACT_USD DOUBLE,
PLAN_BOH_GROSS DOUBLE,
ACTUAL_BOH_PLN_BK_VARNC_USD DOUBLE,
NET_BOH_PLN_BK_VARNC_USD DOUBLE,
REASON_CODE STRING,
REASON_DESC STRING,
COMMENTARY STRING,
CREATED_BY STRING,
CREATED_DATE STRING,
LAST_UPD_BY STRING,
LAST_UPD_DATE STRING
)
PARTITIONED BY (YEAR INT, PERIOD STRING)
STORED AS AVRO
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/ivis/analytics/inv_visibility_commentary_f/';

CREATE EXTERNAL TABLE ACTUAL_INV_VISIBILITY_F 
(
MATERIAL_NO STRING,
AFFILIATE_CODE STRING,
D56_ITEM_NO STRING,
CAL_PERIOD INT,
SOURCE_TYPE STRING,
PLANT_ID STRING,
COMPANY_CODE STRING,
ACTUAL_UNITS DOUBLE,
ACTUAL_VALUE DOUBLE,
ACTUAL_VALUE_USD DOUBLE,
PLAN_VALUE_USD DOUBLE,
UPDATE_VALUE_USD DOUBLE,
STD_LOCAL_COST DOUBLE,
NET_TCGM_VALUE_USD DOUBLE,
CEU DOUBLE,
CREATED_BY STRING,
CREATED_DATE DATE,
LAST_UPD_BY STRING,
LAST_UPD_DATE DATE
)
PARTITIONED BY (INVENTORY_TYPE STRING,YEAR INT, PERIOD INT)
STORED AS AVRO
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/ivis/analytics/actual_inv_visibility_f/';

CREATE EXTERNAL TABLE PLN_UPD_GAP_INV_VISIBILITY_F 
(
MATERIAL_NO STRING,
AFFILIATE_CODE STRING,
D56_ITEM_NO STRING,
CAL_PERIOD STRING,
SOURCE_TYPE STRING,
PLAN_UNITS DOUBLE,
LOCAL_PLAN_VALUE DOUBLE,
PLAN_VALUE_USD DOUBLE,
STD_LOCAL_CURRENCY STRING,
NET_TCGM_VALUE_USD DOUBLE,
CREATED_BY STRING,
CREATED_DATE DATE,
LAST_UPD_BY STRING,
LAST_UPD_DATE DATE
)
PARTITIONED BY (INVENTORY_TYPE STRING,YEAR INT, PERIOD INT)
STORED AS AVRO
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/ivis/analytics/pln_upd_gap_inv_visibility_f/';

CREATE EXTERNAL TABLE FIN_ADJUST_INV_VISIBILITY_F 
(
MATERIAL_NO STRING,
AFFILIATE_CODE STRING,
D56_ITEM_NO STRING,
CAL_PERIOD INT,
SOURCE_TYPE STRING,
ACTUAL_VALUE_USD DOUBLE,
CREATED_BY STRING,
CREATED_DATE DATE,
LAST_UPD_BY STRING,
LAST_UPD_DATE DATE
)
PARTITIONED BY (INVENTORY_TYPE STRING,YEAR INT, PERIOD INT)
STORED AS AVRO
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/ivis/analytics/fin_adjust_inv_visibility_f/';

CREATE EXTERNAL TABLE STG_AUDIT_DM_LOAD_TIME
(
CURRENT_LOAD_PERIOD DATE,
PREVIOUS_LOAD_PERIOD DATE,
COMPLETE_STATUS STRING,
INSERT_DT TIMESTAMP,
UPDATE_DT TIMESTAMP        
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/ivis/staging/hive/stg_audit_dm_load_time/';

CREATE EXTERNAL TABLE INV_VISIBILITY_VARNC_F
(
AFFILIATE_CODE STRING,
GROUP_DESC STRING,
AFFILIATE_DESC STRING,
PLANT_ID STRING,
COMPANY_CODE STRING,
ACTUAL_BOH_ACT_BK_USD DOUBLE,
ACTUAL_BOH_PLN_BK_USD DOUBLE,
ACTUAL_BOH_UPD_BK_USD DOUBLE,
NET_BOH_PLN_USD DOUBLE,
NET_BOH_ACT_USD DOUBLE,
PLAN_BOH_GROSS DOUBLE,
ACTUAL_BOH_PLN_BK_VARNC_USD DOUBLE,
NET_BOH_PLN_BK_VARNC_USD DOUBLE,
CREATED_BY STRING,
CREATED_DATE DATE,
LAST_UPD_BY STRING,
LAST_UPD_DATE DATE
)
PARTITIONED BY (YEAR INT, PERIOD INT)
STORED AS AVRO
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/ivis/analytics/inv_visibility_varnc_f/';

CREATE TABLE TMP_INV_VISIBILITY
(
AFFILIATE_CODE STRING ,
GROUP_DESC STRING ,
AFFILIATE_DESC STRING ,
PLANT_ID STRING,
COMPANY_CODE STRING,
ACTUAL_BOH_ACT_BK_USD DOUBLE,
ACTUAL_BOH_PLN_BK_USD DOUBLE ,
ACTUAL_BOH_UPD_BK_USD DOUBLE ,
NET_TCGM_VALUE_USD DOUBLE 
)
PARTITIONED BY (TYPE STRING, YEAR INT, MONTH INT)
STORED AS AVRO
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/ivis/temp/tmp_inv_visibility/';

CREATE EXTERNAL TABLE IVIS_AFF_EMAIL_GRP
(
AFFILIATE_CODE STRING,
PLANT_ID  STRING,
SC_EMAIL_TO_GRP STRING,
SC_EMAIL_BCC_GRP STRING,
EMAIL_DEFAULT_GRP STRING,
CREATED_BY STRING,
CREATED_DT DATE
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/ivis/analytics/ivis_aff_email_grp/';

CREATE EXTERNAL TABLE REPORT_USER_SECURITY
(
USERID STRING,
FIRSTNAME STRING,
LASTNAME STRING,
UPI_NUMBER STRING,
ACCESS STRING,
LOCATION STRING,
ACCESS_TYPE STRING,
TCGM STRING,
DELETE_FLAG STRING,
CREATED_BY STRING,
CREATED_DATE DATE
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/ivis/analytics/report_user_security/';

CREATE EXTERNAL TABLE COST_OVERRIDE_HISTORY
(
MATERIAL_ID	STRING,
MATERIAL_DESC STRING,
MATERIAL_TYP STRING,
PLANT_ID STRING,
COMPANY_CDE	STRING,
SUPPLY_PLANT_ID	STRING,
SUPPLY_COMPANY_CDE STRING,
WAREHOUSE_CDE STRING,
JDA_D56_ITEM_NO STRING,
SAP_D56_ITEM_NO	STRING,
JDA_AFF_CDE	STRING,
STD_COST DOUBLE,
BASE_UOM STRING,
AMT_LOCAL_CURR DOUBLE,
CURRENCY STRING,
TOTAL_STOCK_QTY	DOUBLE,
COST_OVERRIDE_FLG STRING,
INSERT_DT DATE,
CREATED_BY STRING,
INVENTORY_TYP STRING,
YEAR INT,
PERIOD INT
)
STORED AS AVRO
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/ivis/analytics/cost_override_history/';

CREATE EXTERNAL TABLE COST_OVERRIDE
(
MATERIAL_ID	STRING,
MATERIAL_DESC STRING,
MATERIAL_TYP STRING,
PLANT_ID STRING,
COMPANY_CDE	STRING,
SUPPLY_PLANT_ID	STRING,
SUPPLY_COMPANY_CDE STRING,
WAREHOUSE_CDE STRING,
JDA_D56_ITEM_NO STRING,
SAP_D56_ITEM_NO	STRING,
JDA_AFF_CDE	STRING,
STD_COST DOUBLE,
BASE_UOM STRING,
AMT_LOCAL_CURR DOUBLE,
CURRENCY STRING,
TOTAL_STOCK_QTY	DOUBLE,
COST_OVERRIDE_FLG STRING,
INSERT_DT DATE,
CREATED_BY STRING,
INVENTORY_TYP STRING,
YEAR INT,
PERIOD INT
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
STORED AS TEXTFILE
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/ivis/analytics/cost_override/';


-- REPAIR TABLE --
MSCK REPAIR TABLE LND_INV_ONHAND_DLY;
MSCK REPAIR TABLE LND_INV_ONHAND_MTHLY;
MSCK REPAIR TABLE LND_INV_INTRANSIT_DLY;
MSCK REPAIR TABLE LND_SAP_PLANT_COMPANY_MASTER;
MSCK REPAIR TABLE LND_SAP_MATERIAL_MASTER;
MSCK REPAIR TABLE LND_PRIMARY_PLANT_LOOKUP;
MSCK REPAIR TABLE STG_INV_ONHAND_DLY;
MSCK REPAIR TABLE STG_INV_ONHAND_MTHLY;
MSCK REPAIR TABLE STG_INV_INTRANSIT_DLY;
MSCK REPAIR TABLE STG_SAP_PLANT_COMPANY_MASTER;
MSCK REPAIR TABLE STG_SAP_MATERIAL_MASTER_HISTORY;
MSCK REPAIR TABLE STG_SAP_MATERIAL_MASTER;
MSCK REPAIR TABLE STG_INV_ONHAND_INTRA;
MSCK REPAIR TABLE STG_INV_INTER_INTRANSIT;
MSCK REPAIR TABLE STG_SAP_MATERIAL_DETAIL;
MSCK REPAIR TABLE STG_PRIMARY_PLANT_LOOKUP;
MSCK REPAIR TABLE STG_INV_VISIBILITY;
MSCK REPAIR TABLE ERR_INV_VISIBILITY;
MSCK REPAIR TABLE TMP_MATERIAL_COST;
MSCK REPAIR TABLE TMP_MAT_PRIM_PLANT_COST;
MSCK REPAIR TABLE STG_FIN_MANUAL_ADJUSTMENTS;
MSCK REPAIR TABLE STG_PLAN_UPD_GAP;
MSCK REPAIR TABLE INV_VISIBILITY_COMMENTARY_F;
MSCK REPAIR TABLE ACTUAL_INV_VISIBILITY_F;
MSCK REPAIR TABLE PLN_UPD_GAP_INV_VISIBILITY_F;
MSCK REPAIR TABLE FIN_ADJUST_INV_VISIBILITY_F;
MSCK REPAIR TABLE TMP_INV_VISIBILITY;
MSCK REPAIR TABLE STG_AUDIT_DM_LOAD_TIME;
MSCK REPAIR TABLE INV_VISIBILITY_VARNC_F;
MSCK REPAIR TABLE IVIS_AFF_EMAIL_GRP;
MSCK REPAIR TABLE REPORT_USER_SECURITY;
MSCK REPAIR TABLE COST_OVERRIDE_HISTORY;
MSCK REPAIR TABLE COST_OVERRIDE;