
-- CREATE DATABASE --
CREATE DATABASE IF NOT EXISTS ${hiveconf:DATABASE};  
USE ${hiveconf:DATABASE};


-- DROP TABLE --
DROP TABLE IF EXISTS LND_D56_ITEM_NO;
DROP TABLE IF EXISTS LND_STG_ITEM;
DROP TABLE IF EXISTS LND_STG_LOC_HIERARCHY;


DROP TABLE IF EXISTS LND_EXCHANGE_RATE_D;
DROP TABLE IF EXISTS LND_USR_PERMISSION_MASTER;
DROP TABLE IF EXISTS LND_SCP_WEB_USR_ACCESS_VW;
DROP TABLE IF EXISTS LND_PRCS_BSNS_DAY_CAL;

DROP TABLE IF EXISTS LND_CALENDAR_D;
DROP TABLE IF EXISTS LND_STG_ITEM_ATTR_COMMON;

DROP TABLE IF EXISTS STG_TCGM;

DROP TABLE IF EXISTS LND_DEFAULT_D56_ITEM_NO;
DROP TABLE IF EXISTS LND_DEFAULT_STG_ITEM;
DROP TABLE IF EXISTS LND_DEFAULT_STG_LOC_HIERARCHY;

CREATE EXTERNAL TABLE IF NOT EXISTS LND_D56_ITEM_NO(
INVTYPE   STRING,
LISTNO  STRING,
PACKSIZE  STRING,
LABELCODE  STRING,
SIZECODE  STRING,
LISTDESC  STRING,
LINE  STRING,
LINEDESC  STRING,
SUBLINE  STRING,
SUBLINEDESC  STRING,
GROUPCODE  STRING,
GROUPDESC  STRING,
SUBGROUP  STRING,
SUBGROUPDESC  STRING,
FORMCODE  STRING,
FORMCODEDESC  STRING,
PACKCODEDESC  STRING,
CEUUOM  STRING,
CEUFACTOR  STRING,
CREATED_BY  STRING,
CREATION_DATE  STRING,
LAST_UPD_BY  STRING,
LAST_UPD_DATE  STRING,
STATUS  STRING,
SOURCE  STRING,
DATAMART_LAST_UPD_BY  STRING,
DATAMART_LAST_UPD_DATE  STRING,
ORIGINAL_INSERT_DATE  STRING,
LAST_DATE_SENT_RGM  STRING,
LAST_DATE_UPD_WEB  STRING,
LAST_DATE_SENT_VALID  STRING,
ALT_CEUUOM  STRING,
ALT_CEUFACTOR  STRING,
ALT_CEUCOMMENT  STRING)
COMMENT 'D56 Item no table from Oracle JDA through sqoop '
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\001'
STORED AS TEXTFILE
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/landing/jda/lnd_d56_item_no/';

CREATE EXTERNAL TABLE IF NOT EXISTS LND_STG_ITEM(
ITEM_NO  STRING,
DESCR  STRING,
AFFILIATE  STRING,
AFFILIATE_TYPE  STRING,
STD_COST  DOUBLE,
STD_PRICE  DOUBLE,
DISCONTINUE_DATE  STRING,
EFFECTIVE_DATE  STRING,
PREDCSR  STRING,
CEU_FACTOR  INT,
PLAN_ITEM  STRING,
ADD_ITEM  INT,
ABC_CODE  STRING,
MPS  STRING,
DRP  STRING,
MAJOR_BUSINESS  STRING,
SOP_ITEM_FLAG  STRING,
SOP_ATTRIBUTE1  STRING,
SOP_ATTRIBUTE2  STRING,
SOP_ATTRIBUTE3  STRING,
SOP_ATTRIBUTE4  STRING,
SOP_ATTRIBUTE5  STRING,
SOP_ATTRIBUTE6  STRING,
SOP_ATTRIBUTE7  STRING,
SOP_FAMILY  STRING,
D56_ITEM_NO_OK  STRING,
D56_ITEM_NO  STRING,
D56_INV_TYPE  STRING,
D56_LABEL_CODE  STRING,
D56_PACK_CODE  STRING,
D56_LIST_NBR  STRING,
D56_SIZE_CODE  STRING,
D56_PREV_ITEM  STRING,
D56_SUCC_ITEM  STRING,
D56_CONV_FACTOR_CEU  DOUBLE,
D56_CONV_FACTOR_DESC  STRING,
D56_FORM  STRING,
D56_PACK_CODE_DESC  STRING,
D56_PRODUCT_GROUP  STRING,
D56_PRODUCT_GROUP_DESC  STRING,
D56_PRODUCT_GROUP_SUBGROUP  STRING,
D56_PRODUCT_GROUP_SBGRP_DESC  STRING,
D56_PRODUCT_LINE  STRING,
D56_PRODUCT_LINE_DESC  STRING,
D56_PROD_SUBLINE  STRING,
D56_PROD_SUBLINE_DESC  STRING,
ABT_INTERNAL_SOURCE  STRING,
SOURCE_LOC  STRING,
PUR_ITEM_NO  STRING,
PUR_UOM  STRING,
STOCK_UOM  STRING,
SELL_UOM  STRING,
PUR_STOCK_CONV  DOUBLE,
SELL_STOCK_CONV  DOUBLE,
STORAGE_TYPE  STRING,
SOURCE_LOC_EMAIL  STRING,
PRODMGR_EMAIL  STRING,
COMDIR_EMAIL  STRING,
SAMPLE  STRING,
UDC_DELETEME  DOUBLE,
ATTRIBUTE1  STRING,
ATTRIBUTE2  STRING,
ATTRIBUTE3  STRING,
ATTRIBUTE4  STRING,
ATTRIBUTE5  STRING,
ATTRIBUTE6  STRING,
ATTRIBUTE7  STRING,
AFF_LEVEL1  STRING,
AFF_LEVEL2  STRING,
AFF_LEVEL3  STRING,
AFF_LEVEL4  STRING,
AFF_LEVEL5  STRING,
AFF_LEVEL6  STRING,
AFF_LEVEL7  STRING,
WAREHOUSE_TO  STRING,
ORIG_ITEM_NO  STRING,
AFF_GROUP_CODE  STRING,
AFF_GROUP_DESC  STRING,
CLASS_CODE  STRING,
SS_TOLERANCE  STRING,
REPLEN_PER_YEAR DOUBLE,
INC_ORDER_QTY  DOUBLE,
SHELF_LIFE_DAYS  DOUBLE,
STD_BATCH_SIZE  DOUBLE,
CASE_PER_PAL  DOUBLE,
CASE_UOM  STRING,
CASE_DIM_VOLUME  DOUBLE,
CASE_DIM_LENGTH  DOUBLE,
CASE_DIM_WIDTH  DOUBLE,
CASE_DIM_HEIGHT  DOUBLE,
CASE_WEIGHT DOUBLE,
PALLET_UOM  STRING,
PALLET_DIM  DOUBLE,
PALLET_WEIGHT  DOUBLE,
CASE_PER_TL_PAL  DOUBLE,
CASE_PER_TL_NOPAL  DOUBLE,
CASE_PER_CL_PAL  DOUBLE,
CASE_PER_CL_NOPAL  DOUBLE,
LEADTIME_PUBLISHED  DOUBLE,
INACTIVE_ITEM  STRING,
DELETE_ITEM  STRING,
NEW_ITEM  STRING,
LOT_CONTROL  STRING,
LOT_SIZE  INT,
MANUFCYCLE_TIME  INT,
MASTER_SCHED_CODE  STRING,
MIN_ORDER_QTY  INT,
MIN_BALANCE  INT,
PLANNER_CODE  STRING,
PLANNING_CODE  STRING,
WH_STOCK_CODE  STRING,
POSTPONEMENT  STRING,
ORDER_POLICY_CODE  STRING,
ORDER_SETUP_COST  INT,
DOSAGE_FORM  STRING,
LEADTIME_REPLENISH  DOUBLE,
LEADTIME_MFG DOUBLE,
LEADTIME_PUR  DOUBLE,
LEADTIME_CUSTOMS  DOUBLE,
LEADTIME_QA  DOUBLE,
LEADTIME_TESTING  DOUBLE,
LEADTIME_ACTUAL  DOUBLE,
REC_ID  STRING,
REC_NUM  DOUBLE,
EDIT_CK_OK  STRING,
EDIT_CODE  STRING,
EDIT_ERR_TYPE  STRING,
EDIT_ERR_CNT  DOUBLE,
AFF_INS_USER  STRING,
AFF_INS_DATE_TIME  STRING,
BT_EDIT_USER  STRING,
BT_EDIT_DATE_TIME  STRING,
BT_MAINT_USER  STRING,
BT_MAINT_DATE_TIME  STRING,
WM_LAST_UPD_BY  STRING,
WM_CREATED_BY  STRING,
WM_LAST_UPD_DATE  STRING,
WM_CREATION_DATE  STRING,
WM_RECORD_TYPE  STRING,
HQ_EDIT_DATE  STRING,
HQ_EDIT_PROCESS_ID  STRING,
HQ_ERROR_CODE  STRING,
HQ_ERROR_COUNT  DOUBLE,
HQ_STATUS  STRING,
DATAMART_LAST_UPD_BY  STRING,
DATAMART_LAST_UPD_DATE  STRING,
GL_INV_DIVISION  STRING,
GL_SALES_DIVISION  STRING,
GL_INV_PERFORMANCE  STRING,
GL_SALES_PERFORMANCE  STRING,
INVOICE_LOCATION  STRING,
REPORTING_AFFILIATE  STRING,
SENDING_LOCATION  STRING,
ITEM_TYPE_ID  INT,
STD_COST_CURRENCY  STRING,
TRANSFER_PRICE  DOUBLE,
OTHER_ICB_COST  DOUBLE,
PLAN_YEAR_TRAN_PRICE  DOUBLE,
PLAN_YEAR_OTHER_ICB_COST  DOUBLE,
PLAN_YEAR_STD_COST DOUBLE,
BALANCE_SHEET_ITEM  STRING,
INTRAN_DAYS_TO_PLANNING_OH  STRING,
FORCAST_FINANCIAL_INVENTORY  STRING,
ITEM_COMMENT_FRANCHISE  STRING,
ITEM_COMMENT_SITE  STRING,
LOC  STRING,
ITEM_CODE  STRING,
ORIG_ITEM_CODE  STRING,
ITEM_DIST_TYPE  STRING)
COMMENT 'Item table from Oracle JDA through sqoop '
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\001'
STORED AS TEXTFILE
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/landing/jda/lnd_stg_item/';


CREATE EXTERNAL TABLE IF NOT EXISTS LND_STG_LOC_HIERARCHY(
LEVEL_1_ID  INT,
LEVEL_1_CODE  STRING,
LEVEL_1_DESC  STRING,
LEVEL_1_LABEL_ID  INT,
LEVEL_1_LABEL_DESC  STRING,
LEVEL_2_ID  INT,
LEVEL_2_CODE  STRING,
LEVEL_2_DESC  STRING,
LEVEL_2_LABEL_ID  INT,
LEVEL_2_LABEL_DESC  STRING,
LEVEL_3_ID  INT,
LEVEL_3_CODE  STRING,
LEVEL_3_DESC  STRING,
LEVEL_3_LABEL_ID  INT,
LEVEL_3_LABEL_DESC  STRING,
LEVEL_4_ID  INT,
LEVEL_4_CODE  STRING,
LEVEL_4_DESC  STRING,
LEVEL_4_LABEL_ID  INT,
LEVEL_4_LABEL_DESC  STRING,
LEVEL_5_ID  INT,
LEVEL_5_CODE  STRING,
LEVEL_5_DESC  STRING,
LEVEL_5_LABEL_ID  INT,
LEVEL_5_LABEL_DESC  STRING,
LEVEL_6_ID  INT,
LEVEL_6_CODE  STRING,
LEVEL_6_DESC  STRING,
LEVEL_6_LABEL_ID INT,
LEVEL_6_LABEL_DESC  STRING,
LEVEL_7_ID  INT,
LEVEL_7_CODE  STRING,
LEVEL_7_DESC  STRING,
LEVEL_7_LABEL_ID  INT,
LEVEL_7_LABEL_DESC  STRING,
LEVEL_8_ID  INT,
LEVEL_8_CODE  STRING,
LEVEL_8_DESC  STRING,
LEVEL_8_LABEL_ID  INT,
LEVEL_8_LABEL_DESC  STRING,
LEVEL_9_ID  INT,
LEVEL_9_CODE  STRING,
LEVEL_9_DESC  STRING,
LEVEL_9_LABEL_ID  INT,
LEVEL_9_LABEL_DESC  STRING,
LEVEL_10_ID  INT,
LEVEL_10_CODE  STRING,
LEVEL_10_DESC  STRING,
LEVEL_10_LABEL_ID  INT,
LEVEL_10_LABEL_DESC  STRING,
LOC_TYPE_ID  INT,
LOC_TYPE_CODE  STRING,
LOC_TYPE_DESC  STRING,
LOC_DISTR_TYPE_ID  INT,
LOC_DISTR_TYPE_CODE  STRING,
LOC_DISTR_TYPE_DESC  STRING,
MODEL_ID  INT,
LOH_ADJUSTMENT  STRING,
HOME_CURRENCY  STRING,
INTL_LOC  STRING,
FISCAL_CAL_ID  INT,
FISCAL_CAL_DESC  STRING,
FIN_ACCTNG_MTHS_4_4_5  INT,
RECORD_FLAG  STRING,
DELETE_FLAG  STRING,
FORECAST_MONTH  INT,
HISTORICAL_MONTHS  INT,
GL_ENTITY  STRING,
BUSINESS_GROUP  STRING,
BUSINESS_GROUP_DESC  STRING,
DIVISION  STRING,
DIVISION_DESC  STRING,
AREA  STRING,
AREA_DESC  STRING,
SUB_AREA  STRING,
SUB_AREA_DESC  STRING,
REGION  STRING,
REGION_DESC  STRING,
SUB_REGION  STRING,
SUB_REGION_DESC  STRING,
INTL_DOMESTIC  STRING,
INTL_DOMESTIC_DESC  STRING,
MFG_DISTRIBUTION  STRING,
MFG_DISTRIBUTION_DESC  STRING,
LOCATION_TYPE  STRING,
LOCATION_TYPE_DESC  STRING,
AFFILIATE  STRING,
AFFILIATE_DESC  STRING,
SUB_AFFILIATE  STRING,
SUB_AFFILIATE_DESC  STRING,
LOC  STRING,
LOC_DESC  STRING,
OTHER  STRING,
OTHER_DESC  STRING,
CREATED_BY  STRING,
CREATION_DATE  STRING,
LAST_UPD_BY  STRING,
LAST_UPD_DATE  STRING,
DATAMART_LAST_UPD_BY  STRING,
DATAMART_LAST_UPD_DATE  STRING,
WH_LEVEL_PLNG_FLAG  STRING,
SENDING_SCHD_SHIP_FLAG  STRING,
ALLOW_ICB_METHOD_FOR_INTRANSIT  STRING,
MAJOR_SOURCE_SYSTEM  STRING,
REPORTING_AFFILIATE_DEFAULT  STRING,
GL_SALES_DIVISION_DEFAULT  STRING,
GL_INV_PERFORMANCE_DEFAULT  STRING,
GL_SALES_PERFORMANCE_DEFAULT  STRING,
INVOICE_LOCATION_DEFAULT  STRING,
ALTER_PLANT_DEFAULT  STRING,
WIP_COST_METHOD  STRING,
INV_RPTG_CURRENCY  STRING)
COMMENT 'Stage item location hierarchy  table from Oracle JDA through sqoop '
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\001'
STORED AS TEXTFILE
LOCATION  '/data/mosc/${hiveconf:ENV_VAR}/landing/jda/lnd_stg_loc_hierarchy/';



CREATE EXTERNAL TABLE IF NOT EXISTS LND_EXCHANGE_RATE_D(
EXCHANGE_RATE_F_PK  INT,
DM_LOAD_TIME  STRING,
DM_LOAD_USER  STRING,
DM_UPDATE_TIME  STRING,
DM_UPDATE_USER  STRING,
POSTING_AGENT_INSERT  STRING,
CONVERSION_FROM_CODE  STRING,
CONVERSION_TO_CODE  STRING,
CONVERSTION_FROM_DESCR  STRING,
CONVERSTION_TO_DESCR  STRING,
PLAN_AVG_EXCHANGE_RATE  DOUBLE,
PLAN_BOOK_EXCHANGE_RATE  DOUBLE,
UPDATE_AVG_EXCHANGE_RATE  DOUBLE,
UPDATE_BOOK_EXCHANGE_RATE  DOUBLE,
ACTUAL_AVG_EXCHANGE_RATE  DOUBLE,
ACTUAL_BOOK_EXCHANGE_RATE  DOUBLE,
FB_AVG_EXCHANGE_RATE  DOUBLE,
FB_BOOK_EXCHANGE_RATE  DOUBLE,
DATE_FK  INT,
ACT_CUR_MONTH_EXCHANGE_RATE  DOUBLE,
PLAN_AVG_DEFAULT_EXCH_RATE  DOUBLE,
PLAN_BOOK_DEFAULT_EXCH_RATE  DOUBLE,
UPDATE_AVG_DEFAULT_EXCH_RATE  DOUBLE,
UPDATE_BOOK_DEFAULT_EXCH_RATE  DOUBLE,
MAJOR_BUSINESS  STRING,
CONSTANT_AVG_EXCHANGE_RATE  DOUBLE,
CONSTANT_BOOK_EXCHANGE_RATE  DOUBLE,
LBE_AVG_EXCHANGE_RATE  DOUBLE,
LBE_BOOK_EXCHANGE_RATE  DOUBLE,
CONST_NYP_AVG_EXCHANGE_RATE DOUBLE,
CONST_NYP_BOOK_EXCHANGE_RATE  DOUBLE,
PYR_AVG_EXCHANGE_RATE  DOUBLE,
PYR_BOOK_EXCHANGE_RATE DOUBLE)
COMMENT 'Exchange rate table from Oracle JDA through sqoop '
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\001'
STORED AS TEXTFILE
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/landing/jda/lnd_exchange_rate_d/';

CREATE EXTERNAL TABLE IF NOT EXISTS LND_USR_PERMISSION_MASTER(
USR_ID  INT,
USR_FRST_NM  STRING,
USR_LST_NM  STRING,
USR_MDDL_NM  STRING,
USR_SCM_ID  STRING,
HEADQUATER_USER  STRING,
CREATED_BY  STRING,
CREATED_DATE  STRING,
LAST_UPD_BY  STRING,
LAST_UPD_DATE  STRING,
USR_COUNTRY  STRING,
ACTIVE_USER  STRING,
LAST_ACCESS_DATE  STRING,
OPS_USER  STRING,
USR_EML_ID STRING)
COMMENT 'usr_permission_master table from Oracle JDA through sqoop '
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\001'
STORED AS TEXTFILE
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/landing/jda/lnd_usr_permission_master/';

CREATE EXTERNAL TABLE IF NOT EXISTS LND_SCP_WEB_USR_ACCESS_VW(
LOC STRING,        
USR_SCM_ID STRING,
SCREEN_NAME STRING)
COMMENT 'scp_web_usr_access_vw table from Oracle JDA through sqoop '
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\001'
STORED AS TEXTFILE
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/landing/jda/lnd_scp_web_usr_access_vw';


CREATE EXTERNAL TABLE IF NOT EXISTS LND_PRCS_BSNS_DAY_CAL (
CALENDAR_DT  STRING,           
BSNS_DAY_NUM  INT,        
BSNS_CYCLE_ID  INT,         
BSNS_DAY_CAL_DESC STRING,      
CREATED_BY STRING,             
CREATED_DT  STRING,            
GIR_RECONCILIATION_END_DATE STRING,    
LAST_UPD_BY  STRING,      
LAST_UPD_DATE TIMESTAMP)   
COMMENT 'prcs_bsns_day_cal table from Oracle JDA through sqoop '
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\001'
STORED AS TEXTFILE
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/landing/jda/lnd_prcs_bsns_day_cal/';



CREATE EXTERNAL TABLE IF NOT EXISTS LND_STG_ITEM_ATTR_COMMON(
ITEM_NO  STRING,
SCALE_FACTOR  INT,
DRP_OVR  STRING,
ABT_INTERNAL_SOURCE_OVR  STRING,
SOURCE_LOC_OVR  STRING,
SOP_ITEM_FLAG_OVR  STRING,
PUR_ITEM_NO_OVR  STRING,
REPORTING_AFFILIATE_OVR  STRING,
PUR_STOCK_CONV_OVR  STRING,
INACTIVE_ITEM_OVR  STRING,
GL_INV_DIVISION_OVR  STRING,
GL_SALES_DIVISION_OVR  STRING,
CEU_FACTOR_OVR  STRING,
WAREHOUSE_TO_OVR  STRING,
ABC_CODE_OVR  STRING,
PREDECESSOR_OVR  STRING,
CREATED_BY  STRING,
CREATION_DATE  STRING,
LAST_UPD_BY  STRING,
LAST_UPD_DATE  STRING,
LAST_UPD_BY_WEB  STRING,
LAST_UPD_DATE_WEB  STRING,
DATAMART_LAST_UPD_DATE  STRING,
BUSINESS_TYPE  STRING,
FUTURE_STD_COST  DOUBLE,
SAP_MAT_STATUS STRING)
COMMENT 'stg_item_attr_common table from Oracle JDA through sqoop '
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\001'
STORED AS TEXTFILE
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/landing/jda/lnd_stg_item_attr_common/';


CREATE EXTERNAL TABLE IF NOT EXISTS STG_TCGM(
REPORTING_AFFILIATE STRING,
INVENTORY_TYPE STRING,
LIST_NO STRING,
LABEL_CODE STRING,
SIZE_CODE STRING,
PACK_SIZE STRING,
D56_ITEM_NO STRING,
MONTH_DATE STRING,
FACT DOUBLE,
CREATED_BY STRING,
CREATION_DATE STRING,
LAST_UPD_BY STRING,
LAST_UPD_DATE STRING,
DATAMART_LAST_UPD_BY STRING,
DATAMART_LAST_UPD_DATE TIMESTAMP)
COMMENT 'stg_tcgm from Oracle JDA through sqoop '
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\001'
STORED AS TEXTFILE
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/securedata/stg_tcgm/';


CREATE EXTERNAL TABLE IF NOT EXISTS LND_CALENDAR_D(
CALENDAR_D_PK  INT,
CALENDAR_DATE  STRING,
DAY_IN_WEEK  INT,
DAY_IN_MONTH  INT,
DAY_IN_YEAR  INT,
DAY_NAME  STRING,
MONTH_NAME  STRING,
MONTH_IN_YEAR  INT,
WEEK_IN_YEAR  INT,
DAYS_SINCE_JAN1990  INT,
QUARTER  STRING,
YEAR  INT,
YEAR_WEEK_CODE  INT,
YEAR_MONTH_CODE  INT,
YEAR_QUARTER_CODE  INT,
FISCAL_YEAR  INT,
FISCAL_QUARTER  STRING,
DAY_AGO  STRING,
WEEK_AGO  STRING,
MONTH_AGO  STRING,
QUARTER_AGO  STRING,
YEAR_AGO  STRING,
TWO_YEARS_AGO  STRING,
TWO_QUARTERS_AGO  STRING,
THREE_QUARTERS_AGO  STRING,
YEAR_MONTH_DESC  STRING,
PERIOD_KEY  STRING,
FIRST_DAY_OF_MONTH  STRING,
DM_LOAD_TIME  STRING,
DM_LOAD_USER  STRING,
DM_UPDATE_TIME  STRING,
DM_UPDATE_USER  STRING,
POSTING_AGENT_INSERT STRING)
COMMENT 'Calendar  table from Oracle JDA through sqoop '
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\001'
STORED AS TEXTFILE
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/landing/jda/lnd_calendar_d/';

CREATE EXTERNAL TABLE IF NOT EXISTS LND_DEFAULT_D56_ITEM_NO(
  INVTYPE STRING,
  LISTNO STRING,
  PACKSIZE STRING,
  LABELCODE STRING,
  SIZECODE STRING,
  LISTDESC STRING,
  GROUPCODE STRING,
  GROUPDESC STRING,
  LINE STRING,
  LINEDESC STRING,
  SUBLINE STRING,
  SUBLINEDESC STRING,
  SUBGROUP STRING,
  SUBGROUPDESC STRING,
  FORMCODE STRING,
  FORMCODEDESC STRING,
  PACKCODEDESC STRING,
  CEUUOM STRING,
  CEUFACTOR STRING,
  STATUS STRING,
  ALT_CEUUOM STRING,
  ALT_CEUFACTOR STRING
)
COMMENT 'This is the staging table for lnd_dummy_stg_item_no'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/landing/jda/lnd_default_d56_item_no/';


CREATE EXTERNAL TABLE IF NOT EXISTS LND_DEFAULT_STG_ITEM(
ITEM_NO STRING,
DESCR  STRING,
AFFILIATE                     STRING,
AFFILIATE_TYPE  STRING,
SOP_ITEM_FLAG                 STRING,
D56_ITEM_NO                   STRING,
D56_INV_TYPE                  STRING,
D56_LIST_NBR                  STRING,
D56_PACK_CODE                 STRING,
D56_LABEL_CODE                STRING,
D56_SIZE_CODE                 STRING,
D56_PRODUCT_GROUP             STRING,
D56_PRODUCT_GROUP_DESC        STRING,
D56_PRODUCT_GROUP_SUBGROUP    STRING,
D56_PRODUCT_GROUP_SBGRP_DESC  STRING,
D56_PRODUCT_LINE              STRING,
D56_PRODUCT_LINE_DESC         STRING,
D56_PROD_SUBLINE              STRING,
D56_PROD_SUBLINE_DESC         STRING,
INACTIVE_ITEM                 STRING,
DELETE_ITEM                   STRING,
ITEM_CODE STRING,
CEU_FACTOR INT,
ITEM_TYPE_ID INT
)
COMMENT 'This is the staging table for lnd_dummy_stg_item'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION '/data/mosc/${hiveconf:ENV_VAR}/landing/jda/lnd_default_stg_item';


CREATE EXTERNAL TABLE IF NOT EXISTS LND_DEFAULT_STG_LOC_HIERARCHY(
LEVEL_1_ID  INT,
LEVEL_1_CODE  STRING,
LEVEL_1_DESC  STRING,
LEVEL_1_LABEL_ID  INT,
LEVEL_1_LABEL_DESC  STRING,
LEVEL_2_ID  INT,
LEVEL_2_CODE  STRING,
LEVEL_2_DESC  STRING,
LEVEL_2_LABEL_ID  INT,
LEVEL_2_LABEL_DESC  STRING,
LEVEL_3_ID  INT,
LEVEL_3_CODE  STRING,
LEVEL_3_DESC  STRING,
LEVEL_3_LABEL_ID  INT,
LEVEL_3_LABEL_DESC  STRING,
LEVEL_4_ID  INT,
LEVEL_4_CODE  STRING,
LEVEL_4_DESC  STRING,
LEVEL_4_LABEL_ID  INT,
LEVEL_4_LABEL_DESC  STRING,
LEVEL_5_ID  INT,
LEVEL_5_CODE  STRING,
LEVEL_5_DESC  STRING,
LEVEL_5_LABEL_ID  INT,
LEVEL_5_LABEL_DESC  STRING,
LEVEL_6_ID  INT,
LEVEL_6_CODE  STRING,
LEVEL_6_DESC  STRING,
LEVEL_6_LABEL_ID INT,
LEVEL_6_LABEL_DESC  STRING,
LEVEL_7_ID  INT,
LEVEL_7_CODE  STRING,
LEVEL_7_DESC  STRING,
LEVEL_7_LABEL_ID  INT,
LEVEL_7_LABEL_DESC  STRING,
LEVEL_8_ID  INT,
LEVEL_8_CODE  STRING,
LEVEL_8_DESC  STRING,
LEVEL_8_LABEL_ID  INT,
LEVEL_8_LABEL_DESC  STRING,
LEVEL_9_ID  INT,
LEVEL_9_CODE  STRING,
LEVEL_9_DESC  STRING,
LEVEL_9_LABEL_ID  INT,
LEVEL_9_LABEL_DESC  STRING,
LEVEL_10_ID  INT,
LEVEL_10_CODE  STRING,
LEVEL_10_DESC  STRING,
LEVEL_10_LABEL_ID  INT,
LEVEL_10_LABEL_DESC  STRING,
LOC_TYPE_ID  INT,
LOC_TYPE_CODE  STRING,
LOC_TYPE_DESC  STRING,
LOC_DISTR_TYPE_ID  INT,
LOC_DISTR_TYPE_CODE  STRING,
LOC_DISTR_TYPE_DESC  STRING,
MODEL_ID  INT,
LOH_ADJUSTMENT  STRING,
HOME_CURRENCY  STRING,
INTL_LOC  STRING,
FISCAL_CAL_ID  INT,
FISCAL_CAL_DESC  STRING,
FIN_ACCTNG_MTHS_4_4_5  INT,
RECORD_FLAG  STRING,
DELETE_FLAG  STRING,
FORECAST_MONTH  INT,
HISTORICAL_MONTHS  INT,
GL_ENTITY  STRING,
BUSINESS_GROUP  STRING,
BUSINESS_GROUP_DESC  STRING,
DIVISION  STRING,
DIVISION_DESC  STRING,
AREA  STRING,
AREA_DESC  STRING,
SUB_AREA  STRING,
SUB_AREA_DESC  STRING,
REGION  STRING,
REGION_DESC  STRING,
SUB_REGION  STRING,
SUB_REGION_DESC  STRING,
INTL_DOMESTIC  STRING,
INTL_DOMESTIC_DESC  STRING,
MFG_DISTRIBUTION  STRING,
MFG_DISTRIBUTION_DESC  STRING,
LOCATION_TYPE  STRING,
LOCATION_TYPE_DESC  STRING,
AFFILIATE  STRING,
AFFILIATE_DESC  STRING,
SUB_AFFILIATE  STRING,
SUB_AFFILIATE_DESC  STRING,
LOC  STRING,
LOC_DESC  STRING,
OTHER  STRING,
OTHER_DESC  STRING,
CREATED_BY  STRING,
CREATION_DATE  STRING,
LAST_UPD_BY  STRING,
LAST_UPD_DATE  STRING,
DATAMART_LAST_UPD_BY  STRING,
DATAMART_LAST_UPD_DATE  STRING,
WH_LEVEL_PLNG_FLAG  STRING,
SENDING_SCHD_SHIP_FLAG  STRING,
ALLOW_ICB_METHOD_FOR_INTRANSIT  STRING,
MAJOR_SOURCE_SYSTEM  STRING,
REPORTING_AFFILIATE_DEFAULT  STRING,
GL_SALES_DIVISION_DEFAULT  STRING,
GL_INV_PERFORMANCE_DEFAULT  STRING,
GL_SALES_PERFORMANCE_DEFAULT  STRING,
INVOICE_LOCATION_DEFAULT  STRING,
ALTER_PLANT_DEFAULT  STRING,
WIP_COST_METHOD  STRING,
INV_RPTG_CURRENCY  STRING)
COMMENT 'Stage item location hierarchy  table from Oracle JDA through sqoop '
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE
LOCATION  '/data/mosc/${hiveconf:ENV_VAR}/landing/jda/lnd_default_stg_loc_hierarchy';

MSCK REPAIR TABLE LND_D56_ITEM_NO;
MSCK REPAIR TABLE LND_STG_ITEM;
MSCK REPAIR TABLE LND_STG_LOC_HIERARCHY;


MSCK REPAIR TABLE LND_EXCHANGE_RATE_D;
MSCK REPAIR TABLE LND_USR_PERMISSION_MASTER;
MSCK REPAIR TABLE LND_SCP_WEB_USR_ACCESS_VW;
MSCK REPAIR TABLE LND_PRCS_BSNS_DAY_CAL;

MSCK REPAIR TABLE LND_CALENDAR_D;
MSCK REPAIR TABLE LND_STG_ITEM_ATTR_COMMON;

MSCK REPAIR TABLE STG_TCGM;

MSCK REPAIR TABLE LND_DEFAULT_D56_ITEM_NO;
MSCK REPAIR TABLE LND_DEFAULT_STG_ITEM;
MSCK REPAIR TABLE LND_DEFAULT_STG_LOC_HIERARCHY;