CREATE TABLE IF NOT EXISTS [[APP_HBASE_DB_NAME]].UPLOAD_PLAN_UPD (
affiliate_code varchar,
type varchar,
year varchar,
sap_material_no varchar,
upload_id  varchar,
units_jan varchar,
units_feb varchar,
units_mar varchar,
units_apr varchar,
units_may varchar,
units_jun varchar,
units_jul varchar,
units_aug varchar,
units_sep varchar,
units_oct varchar,
units_nov varchar,
units_dec varchar,
file_name varchar,
comment varchar,
created_by varchar,
created_date varchar,
delete_flag varchar,
CONSTRAINT pk PRIMARY KEY (affiliate_code,type,year,sap_material_no,upload_id) ) SALT_BUCKETS = 3,COMPRESSION='SNAPPY';


CREATE  TABLE IF NOT EXISTS [[APP_HBASE_DB_NAME]].UPLOAD_PLAN_UPD_GAP (
affiliate_code varchar,
type varchar,
year varchar,
group_desc varchar,
upload_id  varchar,
usd_val_jan varchar,
usd_val_feb varchar,
usd_val_mar varchar,
usd_val_apr varchar,
usd_val_may varchar,
usd_val_jun varchar,
usd_val_jul varchar,
usd_val_aug varchar,
usd_val_sep varchar,
usd_val_oct varchar,
usd_val_nov varchar,
usd_val_dec varchar,
file_name varchar,
comment varchar,
created_by varchar,
created_date varchar,
delete_flag varchar,
CONSTRAINT pk PRIMARY KEY (affiliate_code,type,year,group_desc,upload_id) ) SALT_BUCKETS = 3,COMPRESSION='SNAPPY';


CREATE  TABLE IF NOT EXISTS [[APP_HBASE_DB_NAME]].WEB_PLAN_UPD_GAP (
affiliate_code varchar, 
type varchar, 
year varchar,
sap_material_no varchar,
d56_item_no varchar,
A.affiliate_desc varchar,
A.company_code varchar,
A.plant_id varchar,
A.group_desc varchar,
A.standard_cost_usd varchar,
A.standard_cost_lc varchar,
A.local_currency varchar,
B.units_jan varchar,
B.units_feb varchar,
B.units_mar varchar,
B.units_apr varchar,
B.units_may varchar,
B.units_jun varchar,
B.units_jul varchar,
B.units_aug varchar,
B.units_sep varchar,
B.units_oct varchar,
B.units_nov varchar,
B.units_dec varchar,
B.local_val_jan varchar,
B.local_val_feb varchar,
B.local_val_mar varchar,
B.local_val_apr varchar,
B.local_val_may varchar,
B.local_val_jun varchar,
B.local_val_jul varchar,
B.local_val_aug varchar,
B.local_val_sep varchar,
B.local_val_oct varchar,
B.local_val_nov varchar,
B.local_val_dec varchar,
B.usd_val_jan varchar,
B.usd_val_feb varchar,
B.usd_val_mar varchar,
B.usd_val_apr varchar,
B.usd_val_may varchar,
B.usd_val_jun varchar,
B.usd_val_jul varchar,
B.usd_val_aug varchar,
B.usd_val_sep varchar,
B.usd_val_oct varchar,
B.usd_val_nov varchar,
B.usd_val_dec varchar,
B.comment varchar,
B.created_by varchar,
B.created_date varchar,
B.last_upd_by varchar,
B.last_upd_date varchar,
CONSTRAINT pk PRIMARY KEY (affiliate_code,type,year,sap_material_no,d56_item_no) ) SALT_BUCKETS = 3,COMPRESSION='SNAPPY';



CREATE  TABLE IF NOT EXISTS  [[APP_HBASE_DB_NAME]].UPLOAD_FIN_MANUAL_ADJUSTMENTS (
affiliate_code varchar,
type varchar,
month varchar,
year varchar,
group_desc varchar,
upload_id varchar,
adjusted_value_usd varchar,
file_name varchar,
comment varchar,
created_by varchar,
created_date varchar,
last_upd_by varchar,
last_upd_date varchar,
CONSTRAINT pk PRIMARY KEY (affiliate_code,type,month,year,group_desc,upload_id) ) SALT_BUCKETS = 3,COMPRESSION='SNAPPY';



CREATE  TABLE IF NOT EXISTS  [[APP_HBASE_DB_NAME]].WEB_FIN_MANUAL_ADJUSTMENTS (
affiliate_code varchar not null,
type varchar,
month varchar,
year varchar,
material_no varchar,
d56_item_no varchar,
affiliate_desc varchar,
company_code varchar,
plant_id varchar,
group_desc varchar,
adjusted_value_usd varchar,
comment varchar,
created_by varchar,
created_date varchar,
last_upd_by varchar,
last_upd_date varchar,
CONSTRAINT pk PRIMARY KEY (affiliate_code,type,month,year,d56_item_no) ) SALT_BUCKETS = 3,COMPRESSION='SNAPPY';


