USE ${DATABASE};


INSERT overwrite TABLE INV_VISIBILITY_VARNC_F partition(
YEAR = ${YEAR} , 
PERIOD = ${PERIOD} 
)
SELECT 
AFFILIATE_CODE,
GROUP_DESC,
AFFILIATE_DESC,
PLANT_ID,
COMPANY_CODE,
SUM(ACTUAL_BOH_ACT_BK_USD),
SUM(ACTUAL_BOH_PLN_BK_USD),
SUM(ACTUAL_BOH_UPD_BK_USD),
SUM(NET_BOH_PLN_USD),
SUM(NET_BOH_ACT_USD),
SUM(PLAN_BOH_GROSS),
SUM(ACTUAL_BOH_PLN_BK_VARNC_USD),
SUM(NET_BOH_PLN_BK_VARNC_USD),
       '${USER_NAME}' AS created_by,
       CURRENT_DATE AS created_date,
                       '${USER_NAME}' AS last_upd_by,
                       CURRENT_DATE AS last_upd_date FROM

       (  
SELECT NVL(INV_ACT.AFFILIATE_CODE,NVL(FIN_ADJUST.AFFILIATE_CODE,PLN_GAP.AFFILIATE_CODE)) AS AFFILIATE_CODE,
       NVL(INV_ACT.GROUP_DESC,NVL(FIN_ADJUST.GROUP_DESC,PLN_GAP.GROUP_DESC)) AS GROUP_DESC,
       NVL(INV_ACT.AFFILIATE_DESC,NVL(FIN_ADJUST.AFFILIATE_DESC,PLN_GAP.AFFILIATE_DESC)) AS AFFILIATE_DESC,
       NVL(INV_ACT.PLANT_ID,NVL(FIN_ADJUST.PLANT_ID,PLN_GAP.PLANT_ID)) AS PLANT_ID,
       NVL(INV_ACT.COMPANY_CODE,NVL(FIN_ADJUST.COMPANY_CODE,PLN_GAP.COMPANY_CODE)) AS COMPANY_CODE,
       NVL(INV_ACT.ACTUAL_BOH_ACT_BK_USD,0) + NVL(FIN_ADJUST.ACTUAL_BOH_ACT_BK_USD,0) AS ACTUAL_BOH_ACT_BK_USD,
       NVL(INV_ACT.ACTUAL_BOH_PLN_BK_USD,0) + NVL(FIN_ADJUST.ACTUAL_BOH_PLN_BK_USD,0) AS ACTUAL_BOH_PLN_BK_USD,
       NVL(INV_ACT.ACTUAL_BOH_UPD_BK_USD,0) + NVL(FIN_ADJUST.ACTUAL_BOH_UPD_BK_USD,0) AS ACTUAL_BOH_UPD_BK_USD,
       NVL(PLN_GAP.NET_TCGM_VALUE_USD,0) AS NET_BOH_PLN_USD,
       NVL(INV_ACT.NET_TCGM_VALUE_USD,0) AS NET_BOH_ACT_USD,
       NVL(PLN_GAP.ACTUAL_BOH_PLN_BK_USD,0) AS PLAN_BOH_GROSS,
       NVL(PLN_GAP.ACTUAL_BOH_PLN_BK_USD,0) - ( NVL(INV_ACT.ACTUAL_BOH_PLN_BK_USD,0) + NVL(FIN_ADJUST.ACTUAL_BOH_PLN_BK_USD,0) ) AS ACTUAL_BOH_PLN_BK_VARNC_USD,
       NVL(PLN_GAP.NET_TCGM_VALUE_USD,0) - NVL(INV_ACT.NET_TCGM_VALUE_USD,0) AS NET_BOH_PLN_BK_VARNC_USD
FROM
  (SELECT AFFILIATE_CODE,
          GROUP_DESC,
          AFFILIATE_DESC,
          PLANT_ID,
          COMPANY_CODE,
          ACTUAL_BOH_ACT_BK_USD,
          ACTUAL_BOH_PLN_BK_USD,
          ACTUAL_BOH_UPD_BK_USD,
          NET_TCGM_VALUE_USD,
          YEAR,
          MONTH
   FROM tmp_inv_visibility
   WHERE TYPE ='ACTUAL'
  AND  YEAR = ${YEAR} 
AND MONTH = ${PERIOD} ) INV_ACT
LEFT OUTER JOIN
  (SELECT AFFILIATE_CODE,
          GROUP_DESC,
          AFFILIATE_DESC,
          PLANT_ID,
          COMPANY_CODE,
          ACTUAL_BOH_ACT_BK_USD,
          ACTUAL_BOH_PLN_BK_USD,
          ACTUAL_BOH_UPD_BK_USD,
          NET_TCGM_VALUE_USD,
          YEAR,
          MONTH
   FROM tmp_inv_visibility
   WHERE TYPE ='FIN_ADJUST'
    AND  YEAR = ${YEAR} 
AND MONTH = ${PERIOD} ) FIN_ADJUST ON INV_ACT.AFFILIATE_CODE = FIN_ADJUST.AFFILIATE_CODE
AND INV_ACT.GROUP_DESC = FIN_ADJUST.GROUP_DESC
AND INV_ACT.YEAR = FIN_ADJUST.YEAR
AND INV_ACT.MONTH = FIN_ADJUST.MONTH
LEFT OUTER JOIN
  (SELECT AFFILIATE_CODE,
          GROUP_DESC,
          AFFILIATE_DESC,
          PLANT_ID,
          COMPANY_CODE,
          ACTUAL_BOH_ACT_BK_USD,
          ACTUAL_BOH_PLN_BK_USD,
          ACTUAL_BOH_UPD_BK_USD,
          NET_TCGM_VALUE_USD,
          YEAR,
          MONTH
   FROM tmp_inv_visibility
   WHERE TYPE ='PLN_GAP'
    AND  YEAR = ${YEAR} 
AND MONTH = ${PERIOD} ) PLN_GAP ON INV_ACT.AFFILIATE_CODE = PLN_GAP.AFFILIATE_CODE
AND INV_ACT.GROUP_DESC = PLN_GAP.GROUP_DESC
AND INV_ACT.YEAR = PLN_GAP.YEAR
AND INV_ACT.MONTH = PLN_GAP.MONTH) INV_VARNC 
GROUP BY AFFILIATE_CODE,
GROUP_DESC,
AFFILIATE_DESC,
PLANT_ID,
COMPANY_CODE;