USE ${DATABASE};


INSERT overwrite TABLE tmp_inv_visibility partition(TYPE='PLN_GAP',YEAR=${YEAR},MONTH=${PERIOD})
SELECT PLAN_INV_PLN.AFFILIATE_CODE,
       PLAN_INV_PLN.GROUPDESC AS GROUP_DESC,
       PLAN_INV_PLN.LOC_DESC AS AFFILIATE_DESC,
       NULL AS PLANT_ID,
               NULL AS COMPANY_CODE,
                       SUM(NVL(PLAN_INV_UPD.PLAN_VALUE_USD,PLAN_INV_PLN.PLAN_VALUE_USD)) AS ACTUAL_BOH_ACT_BK_USD,
                       SUM(NVL(PLAN_INV_UPD.PLAN_VALUE_USD,PLAN_INV_PLN.PLAN_VALUE_USD)) AS ACTUAL_BOH_PLN_BK_USD,
                       SUM(NVL(PLAN_INV_UPD.PLAN_VALUE_USD,PLAN_INV_PLN.PLAN_VALUE_USD)) AS ACTUAL_BOH_UPD_BK_USD,
                       SUM(NVL(PLAN_INV_UPD.NET_TCGM_VALUE_USD,PLAN_INV_PLN.NET_TCGM_VALUE_USD)) AS NET_TCGM_VALUE_USD
FROM
  (SELECT AFFILIATE_CODE,
          YEAR AS YEAR,
                  PERIOD AS MONTH,
                  stg_d56.GROUPDESC,
                  stg_loc.LOC_DESC,
                  SUM(PLAN_VALUE_USD) as PLAN_VALUE_USD, 
                  SUM(NET_TCGM_VALUE_USD) AS NET_TCGM_VALUE_USD
   FROM PLN_UPD_GAP_INV_VISIBILITY_F PLAN_INV
   JOIN stg_d56_item_no stg_d56 ON PLAN_INV.d56_item_no = stg_d56.d56_item_no
   JOIN stg_loc_hierarchy stg_loc ON PLAN_INV.AFFILIATE_CODE = stg_loc.loc
   WHERE INVENTORY_TYPE LIKE 'PLAN%'
     AND YEAR=${YEAR}
     AND PERIOD=${PERIOD}
   GROUP BY AFFILIATE_CODE,
            YEAR ,
            PERIOD,
            stg_d56.GROUPDESC,
            stg_loc.LOC_DESC) PLAN_INV_PLN
LEFT OUTER JOIN
  (SELECT AFFILIATE_CODE,
          YEAR AS YEAR,
                  PERIOD AS MONTH,
                  stg_d56.GROUPDESC,
                  stg_loc.LOC_DESC,
                  SUM(PLAN_VALUE_USD) as PLAN_VALUE_USD,
                  SUM(NET_TCGM_VALUE_USD) AS NET_TCGM_VALUE_USD
   FROM PLN_UPD_GAP_INV_VISIBILITY_F PLAN_INV
   JOIN stg_d56_item_no stg_d56 ON PLAN_INV.d56_item_no = stg_d56.d56_item_no
   JOIN stg_loc_hierarchy stg_loc ON PLAN_INV.AFFILIATE_CODE = stg_loc.loc
   WHERE INVENTORY_TYPE LIKE 'UPDATE%'
     AND YEAR=${YEAR}
     AND PERIOD=${PERIOD}
     AND PERIOD>=${UPD_PERIOD}
   GROUP BY AFFILIATE_CODE,
            YEAR ,
            PERIOD,
            stg_d56.GROUPDESC,
            stg_loc.LOC_DESC) PLAN_INV_UPD ON PLAN_INV_PLN.AFFILIATE_CODE = PLAN_INV_UPD.AFFILIATE_CODE
AND PLAN_INV_PLN.YEAR = PLAN_INV_UPD.YEAR
AND PLAN_INV_PLN.MONTH = PLAN_INV_UPD.MONTH
AND PLAN_INV_PLN.GROUPDESC = PLAN_INV_UPD.GROUPDESC
WHERE PLAN_INV_PLN.YEAR=${YEAR}
  AND PLAN_INV_PLN.MONTH=${PERIOD}
GROUP BY PLAN_INV_PLN.AFFILIATE_CODE,
         PLAN_INV_PLN.YEAR ,
                      PLAN_INV_PLN.MONTH,
                                   PLAN_INV_PLN.GROUPDESC,
                                   PLAN_INV_PLN.LOC_DESC,
                                   PLAN_INV_PLN.PLAN_VALUE_USD;