USE ${DATABASE};

INSERT OVERWRITE TABLE COST_OVERRIDE
select
MATERIAL_ID,
MATERIAL_DESC,
MATERIAL_TYP,
PLANT_ID,
COMPANY_CDE,
SUPPLY_PLANT_ID,
SUPPLY_COMPANY_CDE,
WAREHOUSE_CDE,
JDA_D56_ITEM_NO,
SAP_D56_ITEM_NO,
JDA_AFF_CDE,
STD_COST,
BASE_UOM,
AMT_LOCAL_CURR,
CURRENCY,
TOTAL_STOCK_QTY,
COST_OVERRIDE_FLG,
CURRENT_DATE as INSERT_DT,
'${USER_NAME}' as CREATED_BY,
INVENTORY_TYP,
YEAR,
PERIOD
from COST_OVERRIDE_HISTORY 
where COST_OVERRIDE_FLG = 'Y'
and INSERT_DT = CURRENT_DATE;